// <auto-generated />
using System;
using AccesoDatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccesoDatos.Migrations
{
    [DbContext(typeof(StellarContext))]
    [Migration("20260421124039_Telescopios")]
    partial class Telescopios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Negocio.Dominio.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Negocio.Dominio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Negocio.Dominio.Camara", b =>
                {
                    b.HasBaseType("Negocio.Dominio.Equipo");

                    b.Property<string>("Resolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TamanioPixel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TipoSensor")
                        .HasColumnType("int");

                    b.ToTable("Camaras", (string)null);
                });

            modelBuilder.Entity("Negocio.Dominio.Montura", b =>
                {
                    b.HasBaseType("Negocio.Dominio.Equipo");

                    b.ToTable("Monturas", (string)null);
                });

            modelBuilder.Entity("Negocio.Dominio.Ocular", b =>
                {
                    b.HasBaseType("Negocio.Dominio.Equipo");

                    b.ToTable("Oculares", (string)null);
                });

            modelBuilder.Entity("Negocio.Dominio.Telescopio", b =>
                {
                    b.HasBaseType("Negocio.Dominio.Equipo");

                    b.Property<int>("Apertura_mm")
                        .HasColumnType("int");

                    b.Property<int>("DistanciaFocal_mm")
                        .HasColumnType("int");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RelacionFocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Telescopios", (string)null);
                });

            modelBuilder.Entity("Negocio.Dominio.Administrador", b =>
                {
                    b.HasBaseType("Negocio.Dominio.Usuario");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("Negocio.Dominio.Coordinador", b =>
                {
                    b.HasBaseType("Negocio.Dominio.Usuario");

                    b.HasDiscriminator().HasValue("Coordinador");
                });

            modelBuilder.Entity("Negocio.Dominio.Socio", b =>
                {
                    b.HasBaseType("Negocio.Dominio.Usuario");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Socio");
                });

            modelBuilder.Entity("Negocio.Dominio.Usuario", b =>
                {
                    b.OwnsOne("Negocio.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("Negocio.ValueObjects.Password", "Contrasenia", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("Contrasenia")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("Negocio.Dominio.Camara", b =>
                {
                    b.HasOne("Negocio.Dominio.Equipo", null)
                        .WithOne()
                        .HasForeignKey("Negocio.Dominio.Camara", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Negocio.Dominio.Montura", b =>
                {
                    b.HasOne("Negocio.Dominio.Equipo", null)
                        .WithOne()
                        .HasForeignKey("Negocio.Dominio.Montura", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Negocio.Dominio.Ocular", b =>
                {
                    b.HasOne("Negocio.Dominio.Equipo", null)
                        .WithOne()
                        .HasForeignKey("Negocio.Dominio.Ocular", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Negocio.Dominio.Telescopio", b =>
                {
                    b.HasOne("Negocio.Dominio.Equipo", null)
                        .WithOne()
                        .HasForeignKey("Negocio.Dominio.Telescopio", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
